#!/usr/bin/env python3
"""Generate wiki/proposals/index.md: a complete stage list of ALL proposals.

Source of truth is the canonical tc39/proposals tables under raw/proposals/
(and raw/proposals/ecma402/), which are the precedence source for a proposal's
current stage. This catalog is a generated artifact: do NOT edit the output by
hand. It is regenerated by the Update workflow (after pulling raw/proposals).

Deep-read wiki pages (wiki/proposals/<slug>.md) are linked when their
frontmatter title matches a canonical proposal; everything else is plain text
(meaning: not yet read in depth here, only catalogued).
"""

import datetime
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
PROP = ROOT / "raw" / "proposals"
WIKI_PROP = ROOT / "wiki" / "proposals"
OUT = WIKI_PROP / "index.md"

# Stage 4 is filtered to proposals not yet in a ratified ECMAScript edition,
# i.e. those whose "Expected Publication Year" is the current year or later
# (the latest ratified edition is the previous year's). This keeps the Stage 4
# section to the recently-finished, not-yet-shipped batch.
CURRENT_YEAR = datetime.date.today().year

LINK_TEXT = re.compile(r"\[([^\]]+)\]")
STAGE_HEADER = re.compile(r"^###\s*Stage\s*([0-9.]+)")
ROW = re.compile(r"^\|\s*\[")
STATUS_WORD = re.compile(r"^([A-Za-z]+)")
YEAR = re.compile(r"\b(20\d{2})\b")

# Stage display order.
ORDER = ["4", "3", "2.7", "2", "1", "0", "inactive"]
LABEL = {
    "4": "Stage 4 (finished)",
    "3": "Stage 3",
    "2.7": "Stage 2.7",
    "2": "Stage 2",
    "1": "Stage 1",
    "0": "Stage 0",
    "inactive": "Inactive / Withdrawn",
}


def title_of(cell):
    m = LINK_TEXT.search(cell)
    t = m.group(1) if m else cell.strip()
    return t.replace("`", "").strip()


def norm(t):
    return re.sub(r"[^a-z0-9]", "", t.lower())


def cells_of(line):
    return line.split("|")


def parse_readme(path):
    """Active proposals: stage from '### Stage N' section headers."""
    out = []
    stage = None
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        h = STAGE_HEADER.match(line.strip())
        if h:
            stage = h.group(1)
            continue
        if ROW.match(line) and stage:
            out.append((stage, title_of(cells_of(line)[1]), "", None))
    return out


def parse_flat(path, stage):
    """Single-stage files (finished / stage-1 / stage-0 / inactive)."""
    out = []
    if not path.exists():
        return out
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        if not ROW.match(line):
            continue
        cells = cells_of(line)
        title = title_of(cells[1])
        note = ""
        year = None
        if stage == "inactive" and len(cells) > 3:
            m = STATUS_WORD.match(cells[3].strip())
            note = m.group(1) if m else ""
        if stage == "4":
            ym = YEAR.search(cells[-2]) if len(cells) >= 2 else None
            year = int(ym.group(1)) if ym else None
        out.append((stage, title, note, year))
    return out


def collect(base):
    rows = []
    rows += parse_readme(base / "README.md")
    rows += parse_flat(base / "finished-proposals.md", "4")
    rows += parse_flat(base / "stage-1-proposals.md", "1")
    rows += parse_flat(base / "stage-0-proposals.md", "0")
    rows += parse_flat(base / "inactive-proposals.md", "inactive")
    return rows


# Canonical titles that don't normalize to the wiki page title. Keyed by
# norm(canonical title) -> wiki filename. Extend when a deep-read page's title
# diverges from tc39/proposals' wording.
ALIASES = {
    "recordtuple": "records-and-tuples.md",
    "intleraandmonthcodeproposal": "intl-era-month-code.md",
}


def wiki_page_map():
    """norm(title) -> filename for existing deep-read pages."""
    m = {}
    for pf in WIKI_PROP.glob("*.md"):
        if pf.name == "index.md":
            continue
        title = None
        text = pf.read_text(encoding="utf-8", errors="replace")
        fm = re.search(r"^---\n(.*?)\n---", text, re.DOTALL)
        if fm:
            t = re.search(r"^title:\s*(.+)$", fm.group(1), re.MULTILINE)
            if t:
                title = t.group(1).strip()
        if title:
            m[norm(title)] = pf.name
    for alias_norm, fname in ALIASES.items():
        if (WIKI_PROP / fname).exists():
            m[alias_norm] = fname
    return m


def render_section(rows, pages):
    by_stage = {}
    for stage, title, note, year in rows:
        by_stage.setdefault(stage, []).append((title, note, year))
    lines = []
    shown = 0
    for stage in ORDER:
        items = by_stage.get(stage)
        if not items:
            continue
        items.sort(key=lambda x: x[0].lower())
        if stage == "4":
            # Only Stage 4 not yet in a ratified edition (pub year >= 当年).
            total = len(items)
            items = [it for it in items if it[2] and it[2] >= CURRENT_YEAR]
            heading = (
                f"### Stage 4 — まだ ECMAScript 未収載({CURRENT_YEAR} 年以降に出版予定)"
                f"({len(items)} / 出荷済み含む全 {total} 件)"
            )
        else:
            heading = f"### {LABEL[stage]} ({len(items)})"
        if not items:
            continue
        shown += len(items)
        lines.append(heading)
        lines.append("")
        for title, note, year in items:
            page = pages.get(norm(title))
            label = f"[{title}]({page})" if page else title
            bits = [b for b in (note, f"出版予定 {year}" if year else "") if b]
            suffix = f" — {' / '.join(bits)}" if bits else ""
            lines.append(f"- {label}{suffix}")
        lines.append("")
    return lines, shown


def main():
    pages = wiki_page_map()
    rows262 = collect(PROP)
    rows402 = collect(PROP / "ecma402")

    sec262, n262 = render_section(rows262, pages)
    sec402, n402 = render_section(rows402, pages)

    out = []
    out.append("# 全提案ステージ一覧")
    out.append("")
    out.append(
        "> **生成物**。`tools/extract_proposals.py` が `raw/proposals/`(canonical)から生成。"
        "手で編集しない(Update で `raw/proposals` を pull するたび再生成)。"
    )
    out.append(
        "> 現ステージの一次ソースは raw/proposals。精読済みの提案は "
        "`[Title](<slug>.md)` でページへリンク、未リンクは本 wiki で未精読(カタログのみ)。"
    )
    out.append(
        f"> **Stage 4 はまだ ECMAScript に入っていないもの({CURRENT_YEAR} 年以降に出版予定)だけを掲載**"
        "(出荷済みの finished は省略)。Stage 3 以下は全件。"
    )
    out.append(f"> 掲載件数: ECMA-262 {n262} 件 / ECMA-402 {n402} 件。")
    out.append("")
    out.append("## ECMA-262")
    out.append("")
    out += sec262
    out.append("## ECMA-402")
    out.append("")
    out += sec402

    OUT.write_text("\n".join(out).rstrip("\n") + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}: ECMA-262 {n262} / ECMA-402 {n402}")


if __name__ == "__main__":
    main()
